stages:
  features_calculation:
    cmd: python3 -m pytitanic.features -o features -r data/train.csv -s data/test.csv
    deps:
    - data/test.csv
    - data/train.csv
    - pytitanic/features.py
    outs:
    - features/test_features.csv
    - features/train_features.csv
  model_training:
    cmd: python3 -m pytitanic.model -o results -r features/train_features.csv -s features/test_features.csv
    deps:
    - features/test_features.csv
    - features/train_features.csv
    - pytitanic/model.py
    outs:
    - results/cb-model.cbm
    - results/cb-submission.csv
    metrics:
    - results/cb-metrics.json
